Fix conflict with test-unit-power_assert
test-unit-power_assert defines Test::Unit::PowerAssert.
So when test-unit-power_assert is required before test-unit,
PowerAssert in Test::Unit::Util::BacktraceFilter refers to
Test::Unit::PowerAssert and it causes a following error.

$ ruby -rtest/unit/power_assert -rtest/unit -eexit
.../test/unit/util/backtracefilter.rb:16:in `method': undefined method `start' for class `Module' (NameError)